---
- name: Ensure the destination directory exists
  file:
    path: "{{ dest_path }}"
    state: directory
    mode: "0755"

- name: Clone GitHub repository
  git:
    repo: "{{ repo_url }}"
    dest: "{{ dest_path }}" 
    version: main
    update: no 

- name: Check if docker-compose.yml exists
  stat:
    path: "{{ docker_compose_file }}" 
  register: compose_file

- name: Fail if docker-compose.yml is missing
  fail:
    msg: "docker-compose.yml not found in {{ docker_compose_file | directory }}"
  when: not compose_file.stat.exists
