---
- name: Run Python scripts in Docker container
  community.docker.docker_container_exec:
    container: "beacon"
    command: "/usr/local/bin/python {{ item }}"
  loop:
    - beacon/reindex.py 
      #- beacon/db/extract_filtering_terms.py # Commented out due to a ValueError, needs debugging. To be tested with a new set of JSON files. 

#---
#- name: Run Python scripts in Docker container
#  command: >
#    #docker exec beacon python beacon/db/extract_filtering_terms.py
#    docker exec beacon python beacon/reindex.py && docker exec beacon python beacon/db/extract_filtering_terms.py
